export default [
  {
    key: "meta",
    value: null,
    hasChild: true,
    children: [
      {
        key: "version",
        value: "1.4.2",
        hasChild: false,
        children: null,
        isLong: false,
        isImportant: null,
        depth: 1,
      },
      {
        key: "generated_at",
        value: "2023-10-27T10:00:00Z",
        hasChild: false,
        children: null,
        isLong: false,
        isImportant: null,
        depth: 1,
      },
      {
        key: "environment",
        value: "production",
        hasChild: false,
        children: null,
        isLong: false,
        isImportant: null,
        depth: 1,
      },
    ],
    isLong: true,
    isImportant: false,
    depth: 0,
  },
  {
    key: "user_profile",
    value: null,
    hasChild: true,
    children: [
      {
        key: "id",
        value: 84922,
        hasChild: false,
        children: null,
        isLong: false,
        isImportant: null,
        depth: 1,
      },
      {
        key: "username",
        value: "dev_guru",
        hasChild: false,
        children: null,
        isLong: false,
        isImportant: null,
        depth: 1,
      },
      {
        key: "preferences",
        value: null,
        hasChild: true,
        children: [
          {
            key: "ui_settings",
            value: null,
            hasChild: true,
            children: [
              {
                key: "theme",
                value: "dracula",
                hasChild: false,
                children: null,
                isLong: false,
                isImportant: null,
                depth: 3,
              },
              {
                key: "font_size",
                value: 14,
                hasChild: false,
                children: null,
                isLong: false,
                isImportant: null,
                depth: 3,
              },
              {
                key: "sidebar_collapsed",
                value: false,
                hasChild: false,
                children: null,
                isLong: false,
                isImportant: null,
                depth: 3,
              },
            ],
            isLong: true,
            isImportant: false,
            depth: 2,
          },
          {
            key: "network_config",
            value: null,
            hasChild: true,
            children: [
              {
                key: "gateway_details",
                value: null,
                hasChild: true,
                children: [
                  {
                    key: "ipv4",
                    value: "192.168.1.105",
                    hasChild: false,
                    children: null,
                    isLong: false,
                    isImportant: null,
                    depth: 4,
                  },
                  {
                    key: "subnet_mask",
                    value: "255.255.255.0",
                    hasChild: false,
                    children: null,
                    isLong: false,
                    isImportant: null,
                    depth: 4,
                  },
                  {
                    key: "performance_tuning",
                    value: null,
                    hasChild: true,
                    children: [
                      {
                        key: "max_packet_size",
                        value: 1500,
                        hasChild: false,
                        children: null,
                        isLong: false,
                        isImportant: null,
                        depth: 5,
                      },
                      {
                        key: "timeout_ms",
                        value: 5000,
                        hasChild: false,
                        children: null,
                        isLong: false,
                        isImportant: null,
                        depth: 5,
                      },
                      {
                        key: "advanced_metrics",
                        value: null,
                        hasChild: true,
                        children: [
                          {
                            key: "latency_threshold",
                            value: 45,
                            hasChild: false,
                            children: null,
                            isLong: false,
                            isImportant: null,
                            depth: 6,
                          },
                          {
                            key: "jitter_buffer",
                            value: "adaptive",
                            hasChild: false,
                            children: null,
                            isLong: false,
                            isImportant: null,
                            depth: 6,
                          },
                          {
                            key: "packet_loss_tolerance",
                            value: 0.05,
                            hasChild: false,
                            children: null,
                            isLong: false,
                            isImportant: null,
                            depth: 6,
                          },
                          {
                            key: "encryption_depth",
                            value: "AES-256",
                            hasChild: false,
                            children: null,
                            isLong: false,
                            isImportant: null,
                            depth: 6,
                          },
                          {
                            key: "handshake_retries",
                            value: 3,
                            hasChild: false,
                            children: null,
                            isLong: false,
                            isImportant: null,
                            depth: 6,
                          },
                          {
                            key: "keep_alive_interval",
                            value: 60,
                            hasChild: false,
                            children: null,
                            isLong: false,
                            isImportant: null,
                            depth: 6,
                          },
                        ],
                        isLong: true,
                        isImportant: false,
                        depth: 5,
                      },
                    ],
                    isLong: true,
                    isImportant: false,
                    depth: 4,
                  },
                ],
                isLong: true,
                isImportant: false,
                depth: 3,
              },
            ],
            isLong: true,
            isImportant: false,
            depth: 2,
          },
        ],
        isLong: true,
        isImportant: false,
        depth: 1,
      },
    ],
    isLong: true,
    isImportant: false,
    depth: 0,
  },
];
